import os
from datetime import datetime

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from flask import current_app

from models.portfolio import Portfolio


class ExportService:

    @staticmethod
    def export_pdf(portfolio_id):

        portfolio = Portfolio.query.get(portfolio_id)

        if not portfolio:
            raise Exception("Portfolio not found")

        data = portfolio.data or {}

        hero = data.get("hero", {})
        contact = data.get("contact", {})
        skills = data.get("skills", [])

        project = data.get("project", {})
        experience = data.get("experience", {})
        education = data.get("education", {})

        export_dir = os.path.join(
            current_app.root_path,
            "static",
            "export"
        )

        os.makedirs(export_dir, exist_ok=True)

        # Unique filename to avoid browser cache
        filename = (
            f"portfolio_{portfolio_id}_"
            f"{int(datetime.now().timestamp())}.pdf"
        )

        file_path = os.path.join(export_dir, filename)

        c = canvas.Canvas(file_path, pagesize=letter)

        text = c.beginText(50, 750)
        text.setFont("Helvetica", 11)

        # HEADER
        text.setFont("Helvetica-Bold", 18)
        text.textLine(hero.get("name", ""))

        text.setFont("Helvetica", 12)
        text.textLine(hero.get("title", ""))
        text.textLine("")

        # ABOUT
        text.setFont("Helvetica-Bold", 14)
        text.textLine("ABOUT")

        text.setFont("Helvetica", 11)
        text.textLine(hero.get("bio", ""))
        text.textLine("")

        # CONTACT
        text.setFont("Helvetica-Bold", 14)
        text.textLine("CONTACT")

        text.setFont("Helvetica", 11)
        text.textLine(f"Email: {contact.get('email', '')}")
        text.textLine(f"Phone: {contact.get('phone', '')}")
        text.textLine(f"Location: {contact.get('location', '')}")
        text.textLine(f"Github: {contact.get('github', '')}")
        text.textLine(f"LinkedIn: {contact.get('linkedin', '')}")
        text.textLine("")

        # SKILLS
        text.setFont("Helvetica-Bold", 14)
        text.textLine("SKILLS")

        text.setFont("Helvetica", 11)
        text.textLine(", ".join(skills))
        text.textLine("")

        # PROJECT
        text.setFont("Helvetica-Bold", 14)
        text.textLine("PROJECT")

        text.setFont("Helvetica", 11)
        text.textLine(project.get("title", ""))
        text.textLine(project.get("description", ""))
        text.textLine("")

        # EXPERIENCE
        text.setFont("Helvetica-Bold", 14)
        text.textLine("EXPERIENCE")

        text.setFont("Helvetica", 11)
        text.textLine(experience.get("title", ""))
        text.textLine(experience.get("description", ""))
        text.textLine("")

        # EDUCATION
        text.setFont("Helvetica-Bold", 14)
        text.textLine("EDUCATION")

        text.setFont("Helvetica", 11)
        text.textLine(education.get("degree", ""))
        text.textLine(education.get("college", ""))
        text.textLine("")

        # Footer
        text.textLine("------------------------------------")
        text.textLine("Generated by AI Resume Builder")

        c.drawText(text)
        c.save()

        return f"/static/export/{filename}"